services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    # build: ./backend
    restart: always
    image: ghcr.io/nth-nguyen3006/website_dulichkhanhhoa/flask-backend:latest
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
  
  frontend:
    # build: ./frontend
    restart: always
    image: ghcr.io/nth-nguyen3006/website_dulichkhanhhoa/react-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      # Ánh xạ file cấu hình từ máy chủ vào container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge