services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    # build: ./backend
    restart: always
    image: ghcr.io/NTH-Nguyen3006/flask-backend:latest
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
  
  frontend:
    # build: ./frontend
    restart: always
    image: ghcr.io/NTH-Nguyen3006/react-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge