"""Add BusinessRegistration model

Revision ID: 4cef40b470fb
Revises: e4905c79f359
Create Date: 2026-03-15 22:30:33.877479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4cef40b470fb'
down_revision = 'e4905c79f359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if business_types and registration_status enums exist
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        # Safely create enums in PostgreSQL using DO blocks
        op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'business_types') THEN CREATE TYPE business_types AS ENUM ('HOTEL', 'RESTAURANT', 'ATTRACTION'); END IF; END $$;")
        op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'registration_status') THEN CREATE TYPE registration_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED'); END IF; END $$;")
    else:
        # Fallback for other dialects (e.g. SQLite)
        inspector = sa.inspect(bind)
        existing_enums = [e['name'] for e in inspector.get_enums()]
        
        if 'business_types' not in existing_enums:
            sa.Enum('HOTEL', 'RESTAURANT', 'ATTRACTION', name='business_types').create(bind)
        
        if 'registration_status' not in existing_enums:
            sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='registration_status').create(bind)

    # Determine enum types based on dialect
    if bind.dialect.name == 'postgresql':
        business_types_enum = postgresql.ENUM('HOTEL', 'RESTAURANT', 'ATTRACTION', name='business_types', create_type=False)
        registration_status_enum = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='registration_status', create_type=False)
    else:
        business_types_enum = sa.Enum('HOTEL', 'RESTAURANT', 'ATTRACTION', name='business_types')
        registration_status_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='registration_status')

    # Add foreign key to post_comments with a name only if it doesn't exist
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'post_comments' in existing_tables:
        existing_fks = inspector.get_foreign_keys('post_comments')
        if not any(fk['name'] == 'fk_post_comments_parent' for fk in existing_fks):
            with op.batch_alter_table('post_comments', schema=None) as batch_op:
                batch_op.create_foreign_key('fk_post_comments_parent', 'post_comments', ['parent_id'], ['id'])

    # Create business_registrations table only if it doesn't exist
    if 'business_registrations' not in existing_tables:
        op.create_table('business_registrations',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('user_id', sa.String(length=36), nullable=False),
            sa.Column('business_name', sa.String(length=255), nullable=False),
            sa.Column('tax_code', sa.String(length=50), nullable=False),
            sa.Column('headquarters_address', sa.String(length=255), nullable=False),
            sa.Column('representative_name', sa.String(length=100), nullable=False),
            sa.Column('business_license_url', sa.String(length=255), nullable=False),
            sa.Column('representative_id_front_url', sa.String(length=255), nullable=False),
            sa.Column('representative_id_back_url', sa.String(length=255), nullable=False),
            sa.Column('business_type', business_types_enum, nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('status', registration_status_enum, nullable=True),
            sa.Column('admin_notes', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_registrations')
    
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_comments_parent', type_='foreignkey')

    # ### end Alembic commands ###
