"""Add BusinessRegistration model

Revision ID: 4cef40b470fb
Revises: e4905c79f359
Create Date: 2026-03-15 22:30:33.877479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cef40b470fb'
down_revision = 'e4905c79f359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add foreign key to post_comments with a name
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_post_comments_parent', 'post_comments', ['parent_id'], ['id'])

    # Create business_registrations table
    op.create_table('business_registrations',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('business_name', sa.String(length=255), nullable=False),
        sa.Column('tax_code', sa.String(length=50), nullable=False),
        sa.Column('headquarters_address', sa.String(length=255), nullable=False),
        sa.Column('representative_name', sa.String(length=100), nullable=False),
        sa.Column('business_license_url', sa.String(length=255), nullable=False),
        sa.Column('representative_id_url', sa.String(length=255), nullable=False),
        sa.Column('business_type', sa.Enum('HOTEL', 'RESTAURANT', 'ATTRACTION', name='business_types'), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='registration_status'), nullable=True),
        sa.Column('admin_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_registrations')
    
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_comments_parent', type_='foreignkey')

    # ### end Alembic commands ###
