"""Add customer info to bookings

Revision ID: 6cffc79800fb
Revises: 4cef40b470fb
Create Date: 2026-03-18 13:09:13.414542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cffc79800fb'
down_revision = '4cef40b470fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns already exist
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('bookings')]

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        if 'customer_name' not in columns:
            batch_op.add_column(sa.Column('customer_name', sa.String(length=100), server_default='', nullable=False))
        if 'customer_phone' not in columns:
            batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), server_default='', nullable=False))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if columns exist before dropping
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('bookings')]

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        if 'customer_phone' in columns:
            batch_op.drop_column('customer_phone')
        if 'customer_name' in columns:
            batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
