"""Add customer info to bookings

Revision ID: 6cffc79800fb
Revises: 4cef40b470fb
Create Date: 2026-03-18 13:09:13.414542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cffc79800fb'
down_revision = '4cef40b470fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), server_default='', nullable=False))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), server_default='', nullable=False))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
