"""Add post relationships

Revision ID: e4905c79f359
Revises: 
Create Date: 2026-03-11 16:06:08.755997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4905c79f359'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)
    has_parent_id = 'parent_id' in [c.get('name') for c in insp.get_columns('post_comments')]

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        if not has_parent_id:
            batch_op.add_column(sa.Column('parent_id', sa.String(length=36), nullable=True))
            batch_op.create_foreign_key(None, 'post_comments', ['parent_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
